onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /system_tb/clk
add wave -noupdate /system_tb/resetn
add wave -noupdate /system_tb/mode
add wave -noupdate /system_tb/data_in_TDATA
add wave -noupdate /system_tb/data_in_TVALID
add wave -noupdate /system_tb/data_in_TREADY
add wave -noupdate /system_tb/data_in_TLAST
add wave -noupdate /system_tb/data_out_TDATA
add wave -noupdate /system_tb/data_out_TVALID
add wave -noupdate /system_tb/data_out_TREADY
add wave -noupdate /system_tb/data_out_TLAST
add wave -noupdate /system_tb/fault
add wave -noupdate /system_tb/e
add wave -noupdate /system_tb/r
add wave -noupdate /system_tb/pok_done
add wave -noupdate /system_tb/pok_resetn
add wave -noupdate /system_tb/s_w
add wave -noupdate /system_tb/uut/comm_buf/axi_enable
add wave -noupdate /system_tb/uut/comm_buf/package_cnt
add wave -noupdate /system_tb/uut/comm_buf/data_buf
add wave -noupdate /system_tb/uut/a_inverse_read
add wave -noupdate /system_tb/uut/a_inverse
add wave -noupdate /system_tb/uut/b
add wave -noupdate /system_tb/uut/bit_exp_done
add wave -noupdate /system_tb/uut/bit_exp_en
add wave -noupdate /system_tb/uut/bit_exp_index_valid
add wave -noupdate /system_tb/uut/bit_exp_read_short_b
add wave -noupdate /system_tb/uut/bit_exp_short_b
add wave -noupdate /system_tb/uut/bit_sel_b_done
add wave -noupdate /system_tb/uut/bit_sel_b_en
add wave -noupdate /system_tb/uut/bit_sel_b_load_b
add wave -noupdate /system_tb/uut/bit_sel_b_load_index
add wave -noupdate /system_tb/uut/bit_sel_e_done
add wave -noupdate /system_tb/uut/bit_sel_e_en
add wave -noupdate /system_tb/uut/bit_sel_e_start
add wave -noupdate /system_tb/uut/bit_sel_index_w
add wave -noupdate /system_tb/uut/check_cnt
add wave -noupdate /system_tb/uut/check_done
add wave -noupdate /system_tb/uut/check_ref
add wave -noupdate /system_tb/uut/check_result
add wave -noupdate /system_tb/uut/cnt
add wave -noupdate /system_tb/uut/comm_read_data
add wave -noupdate /system_tb/uut/comm_read_data_2
add wave -noupdate /system_tb/uut/comm_write_data
add wave -noupdate /system_tb/uut/comm_write_data_2
add wave -noupdate /system_tb/uut/data_received
add wave -noupdate /system_tb/uut/data_sent
add wave -noupdate /system_tb/uut/done_half
add wave -noupdate /system_tb/uut/global_cnt
add wave -noupdate /system_tb/uut/global_start_track
add wave -noupdate /system_tb/uut/hash_comp
add wave -noupdate /system_tb/uut/hash_done
add wave -noupdate /system_tb/uut/hash_en
add wave -noupdate /system_tb/uut/hash_input_valid
add wave -noupdate /system_tb/uut/hash_msg
add wave -noupdate /system_tb/uut/hash_output
add wave -noupdate /system_tb/uut/hash_reset
add wave -noupdate /system_tb/uut/hash_check_cnt
add wave -noupdate /system_tb/uut/hash_ref
add wave -noupdate /system_tb/uut/hash_result
add wave -noupdate /system_tb/uut/possible_error
add wave -noupdate /system_tb/uut/matrix_shift_en
add wave -noupdate /system_tb/uut/matrix_shift_out
add wave -noupdate /system_tb/uut/mul_matrix
add wave -noupdate /system_tb/uut/mul_output
add wave -noupdate /system_tb/uut/mul_vector
add wave -noupdate /system_tb/uut/noise_vector
add wave -noupdate /system_tb/uut/number_select
add wave -noupdate /system_tb/uut/op_mode
add wave -noupdate /system_tb/uut/read_en
add wave -noupdate /system_tb/uut/read_en_2
add wave -noupdate /system_tb/uut/received_b
add wave -noupdate /system_tb/uut/row_sel_half_way_done
add wave -noupdate /system_tb/uut/row_sel_done
add wave -noupdate /system_tb/uut/row_sel_en
add wave -noupdate /system_tb/uut/row_sel_index_valid
add wave -noupdate /system_tb/uut/row_sel_read_in
add wave -noupdate /system_tb/uut/selected_b
add wave -noupdate /system_tb/uut/selected_e
add wave -noupdate /system_tb/uut/selected_matrix
add wave -noupdate /system_tb/uut/state
add wave -noupdate /system_tb/uut/write_en
add wave -noupdate /system_tb/uut/write_en_2
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {34155 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 282
configure wave -valuecolwidth 827
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {63 us}
